---
title: "Synergy analysis for mouse Harderian gland radiation tumorigenesis induced by mixed beams whose individual components are simulated galactic cosmic rays"
author: "Yimin Lin, Edward Greg Huang, Mark Ebert, Dae Woong Ham, and Rainer K. Sachs"
date: "3 October 2017"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 1. Introduction

### 1.1. Terminology

### 1.2. Scope of Paper 

### 1.3. Synergy Analysis

## 2. Mathematical and Computational Methods

### 2.1. Open-Source, Freely Available Programs
All customized software we developed for this study are open source and freely available. We utilize the programming language R [(R Core Team 2017)](https://www.r-project.org/), which is primarily designed for statistical computing and graphics. We supplement the base R software environment with "R packages" - curated R code collections loaded from the Comprehensive R Archive Network [(CRAN)](https://cran.r-project.org/). The specific packages used are detailed under Computation Implementation (Section 2.5.). All development of the source code was performed in [RStudio](https://www.rstudio.com/), a integrated development environment for R. The current script and its past iterations are both stored on the online version control repository [GitHub](https://github.com/eghuang/NASAmouseHG). The script is freely offered for use or modification under the [GNU General Public License v3.0](https://github.com/eghuang/NASAmouseHG/blob/master/LICENSE). There is no warranty on the script, implied or otherwise.

### 2.2. IDERs and Hazard Functions: General Approach 

#### 2.2.1. Basic Properties

Let $E(d; \textbf{p})$ represent a standard IDER such that $d$ is dose and $\textbf{p}$ is a vector of adjustable parameters that are calibrated by regression from the data. Let $E_j(d_j; \mathbf{p_j})$ be a MIXDER whose $j^{th}$ component contributed dose $d_j$ to the total mixture dose, with $j = 1, 2, \dots, N$. We denote $E(d; \textbf{p}; L)$ as a MIXDER when LET $L$ is used instead of an integer label $j$. We define an IDER as standard if it satisfies the following properties. (a) $E(d = 0; \textbf{p}) = 0$. (b) It has continuous first and second derivatives at all non-negative dosages including $d = 0$. (c) The IDER must be monotonically increasing in some half-open dose interval $[0, A_j)$ such that $\lim_{d \to \infty} E(d, \textbf{p}) = 1$. Conditions (a) and (c) are necessary by definition of an individual dose effect relationship sans background radiation effects. Additionally, condition (b) is required to calculate $I(d)$ by incremental effect additivity. 

#### 2.2.2. Hazard Functions

All our essential calculations take $E(d; \textbf{p})$ to be given by the equation $E = 1 - exp(-H)$ where $H(d; \textbf{p})$, called the hazard function, obeys the following conditions. (a) $H$ is 0 when $d = 0$. (b) $H$ has continuous first and second derivatives at all non-negative dosages including $d = 0$. (c) $H$ is convex and monotonic increasing. Note that these condtions on $H$ hold if and only if $E$ obeys similar conditions. 

We assume $\lim_{d \to \infty} H  = \infty$ which is equivalent to $\lim_{d \to \infty} E(d, \textbf{p}) = 1$. For purposes of this paper, a curve is convex if it has a positive second derivative, which implies upward curvature. Concavity is the opposite. More general definitions are not needed here. Convexity is desired for $H$ because the resulting IDER will have an upper limit of 1 without additional frivolous parameters.


### 2.3. IDERs Used in This Paper

#### 2.3.1. Motivations

For the purposes for incremental effect additivity, IDERs are ideally smooth and monotionically increasing. The hazard function utilized in Cucinotta & Cacao (2017) allows us to construct IDERs that satisfy these properties with fewer adjustable parameters than in earlier models (Ham 2017). Notably, our resulting IDER parameters are different from zero at significant levels ($p < 10^{-5}$). 

#### 2.3.2. IDERs: Functional Forms

Three IDER variants in this paper are implemented to reflect differing particle types and modeling approaches. We describe the effects of individual HZE particles with IDERs corresponding to the TE approach and the NTE approach. The functional form of the HZE, NTE hazard function is as follows:

$$ H =  0.01 * [aa1 * L * d * exp(-aa2 * L) + (1 - exp(- \phi * d)) * kk1] \quad \text{(2.3.2.1)}$$

Additionally, the HZE, TE hazard function appears as:
$$ H = -0.01 [aate1 * L * d * exp(-aate2 * L)] \quad \text{(2.3.2.2)}$$
Here, $aate1$ and $aate2$ are adjustable parameters with dimensions $\mu$m Gy$^{-1}$ keV$^{-1}$.  

Lastly, we describe an IDER for low-LET particles. We do not use the hazard function to construct this IDER. (#egh note to Ray - why don't we used a NTE/TE model to describe low-LET IDERs?)
$$ I_{low-LET}(d) = 1 - exp(- \beta * d) \quad \text{(2.3.2.3)}$$

### 2.4. Synergy Analysis 

### 2.4.1. Distribution of Mixture Dose Between Mixture Component

#### 2.4.2. Simple versus Incremental Additivity

### 2.5. Computational Implementation  
The data are sourced from Chang et al. (2016) and Alpen et al. (1993, 1994) and implemented as R dataframes throughout the calculations. A number of R packages from the CRAN repository were used, notably `stats` for non-linear regression, `deSolve` for solving differential equations, `mvtnorm` for Monte Carlo simulations, and `ggplot2` for plotting.  

Our computational workflow with respect to R methods and functions is as follows. Various datasets on Harderian gland tumorgenesis are first implemented as R dataframe structures. Inverse variance weighted non-linear least square models are fitted over these dataframes using the Gauss-Newton algorithm inside the function `nls` from the package `stats`. Coefficients extracted from the models with `coef` are used to construct hazard functions in the form of a user-written R function. Standardized IDERs are initialized from these hazard functions as user-written functions following the hazard function equation Eq. (2.2.2.1). These resulting IDERs encompass various 1-ion beam variants (HZE, low-LET) and effect models (TE, NTE + TE).  

Computing $I(d)$ involves calling a user-written R function `calculate_complex_id` that applies incremental effect additivity to mixtures of $N \geq 2$ IDERs, with at most one low-LET IDER. `calculate_complex_id` takes an argument to specify use of either the NTE+TE or the TE model. Calculation of $I(d)$ requires construction of an R vector `dE` with elements corresponding to the derivative of each IDER curve as a function of dose. A one-dimensional root finder `uniroot` is used to find the incremental effect of each IDER. We construct `dI`, a vector corresponding to the numerical derivative of $I(d)$ with respect to mixture dose $d$ by applying Eq. (2.2.2.1) to each element of `dE`. A numerical ODE integrator from `deSolve` is used to integrate `dI` with a Radau method to return a R list of dose-effect coordinates.

Confidence intervals for the calculated baseline MIXDER $I(d)$ are found through Monte Carlo (MC) simulations. A vector of total-mixture dose points is chosen. For each MC iteration, a user-written function `generate_ci` initializes a vector of random parameter value samples for a particular dosage from multivariate distributions determined during IDER fitting. Our MC simulations use $500$ total parameter samples over all selected dose points. These samples are drawn with the `rmvnorm` function from the `mvtnorm` package. An $I(d)$ dose effect relation is calculated at that dosage with `calculate_complex_id` and the sample parameters. When the MC step is completed a 95% confidence interval is constructed at each dose point sorted by effect size. The naive confidence intervals are also computed within `generate_ci` by choosing parameters using each parameter marginal distribution instead of using variance-covariance matrices.

## Works Cited
1.	Bennett PV, NC Cutter and BM Sutherland. "Split-dose exposures versus dual ion exposure in human cell neoplastic transformation." Radiat Environ Biophys 46(2): 119-123. (2007).  

2.	Chang PY, FA Cucinotta, KA Bjornstad, J Bakke, CJ Rosen, N Du, . . . EA Blakely. "Harderian Gland Tumorigenesis: Low-Dose and LET Response." Radiat Res 185(5): 449-460. (2016).  

3.	Cucinotta FA and LJ Chappell. "Non-targeted effects and the dose response for heavy ion tumor induction." Mutat Res 687(1-2): 49-53. (2010).  

4.	Norbury JW, W Schimmerling, TC Slaba, EI Azzam, FF Badavi, G Baiocco, . . . CJ Zeitlin. "Galactic cosmic ray simulation at the NASA Space Radiation Laboratory." Life Sci Space Res (Amst) 8: 38-51. (2016).  

5.	Siranart N, EA Blakely, A Cheng, N Handa and RK Sachs. "Mixed Beam Murine Harderian Gland Tumorigenesis: Predicted Dose-Effect Relationships if neither Synergism nor Antagonism Occurs." Radiat Res 186(6): 577-591. (2016).  
